apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: example-servicemonitor-dev
  namespace: development
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - development
  selector:
    matchLabels:
      app: example-service # SHOULD MATCH WITH TARGET SERVICE
  endpoints:
  - port: "metrics" # SHOULD BE SPECIFIED IN TARGET SERVICE
    path: "/metrics"
    interval: 15s
