apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams-config
  namespace: development
data:
  connectors.yaml: |
    connectors:
      - alertmanagerteams: xxx-incoming-webhook.com/webhook/xxxxxx
