apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-msteams
  namespace: development
  labels:
    app: prometheus-msteams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-msteams
  template:
    metadata:
      labels:
        app: prometheus-msteams
      # checksum annotations can be used when you want the pods to restart automatically after the config changes, it can be done with Helm
      # annotations:
      #  checksum/config: {{ include (print "./msteams-config.yaml") . | sha256sum }}
      #  checksum/msteams-card-template: {{ include (print "./msteams-card-config.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-msteams-config
        - name: card-template-volume
          configMap:
            name: prometheus-msteams-card-template
      containers:
        - name: prometheus-msteams
          image: quay.io/prometheusmsteams/prometheus-msteams:v1.5.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          ports:
            - containerPort: 2000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 0.05
              memory: 512Mi
            requests:
              cpu: 0.02
              memory: 256Mi
          args:
            - -config-file=/etc/config/connectors.yaml
            - -template-file=/etc/template/card.tmpl
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: card-template-volume
              mountPath: /etc/template
