apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: example-servicemonitor-{{ .Values.metadata.env }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    release: {{ .Release.name }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.metadata.namespace }}
  selector:
    matchLabels:
      app: example-service # SHOULD MATCH WITH TARGET SERVICE
  endpoints:
  - port: "metrics" # SHOULD BE SPECIFIED IN TARGET SERVICE
    path: "/metrics"
    interval: 15s
