apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.msteams.name }}-config
  namespace: {{ .Values.metadata.namespace }}
data:
  connectors.yaml: |
    connectors:
      - alertmanagerteams: xxx-incoming-webhook.com/webhook/xxxxxx
