apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.prometheus.rule }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    role: {{ .Values.prometheus.rulesRole }}
spec:
  groups:
    - name: instance.rules
      rules:
        - alert: InstanceDown
          expr: absent(up{job="haproxy-service"}) == 1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Instance {{`{{ $labels.instance }}`}} is down"
            description: "No response from {{`{{ $labels.instance }}`}} for 2 minutes"
    - name: backendErrors
      rules:
        - alert: HighBackendErrors
          expr: haproxy_backend_http_responses_total{code="5xx", proxy=~"dummy-backend|soap-backend"} > 5
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High backend errors on {{`{{ $labels.proxy }}`}}"
            description: "Gettting High backend errors on {{`{{ $labels.proxy }}`}}" 
    #- name: test.rules
    #  rules:
    #  - alert: HighMemoryUsage
    #    expr: vector(1)  # Always true
    #    for: 1m
    #    labels:
    #      severity: warning
    #    annotations:
    #      summary: "This is a test alert firing always"

